### ISSUE TITLE
Cannot access Bootply

### ISSUE THREAD

**Issue by jmeade11** [iatek/bootply#15]
I'm so sorry that I paid money for your service.  9 out of 10 times I can't get to my dashboard, create a bootply or save a bootply.  I just get an "Application Error".  Ironically, I can't even use your "contact us" feature on the website.

I expect an answer as to what you are doing to fix this problem and when will it be fixed!  If you do not provide a satisfactory answer, I want my money back.

**Comment by iatek** [comment]
You email support@bootply.com for this type of issue. The server has been down several times lately due to downtime at the BAAS provider. I'm working diligently to resolve these issues. In the meantime, I'll gladly cancel your account.
